---
# Website information
author:
  name: Anitej Palur
  email: ani@anipalur.com
baseURL: https://anipalur.com/
title: Anitej Palur
defaultContentLanguage: en
languageCode: en-GB
timeZone: Asia/Kuala_Lumpur
copyright: © 2023-2025 Anitej Palur

# Website configuration
theme: coder
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
refLinksNotFoundURL: /404
services:
  rss:
    limit: -1
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true

# Development configuration
module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: assets
build:
  noJSConfigInAssets: true
newContentEditor: code
watch: true
