---
# Blog information
title: Anitej Palur's Blog
description: Anitej Palur's Blog on Medicine and Neuroscience

sidebar:
  subtitle: First-year medical student and aspiring neurosurgeon
  avatar:
    src: img/avatar.png
    local: true

article:
  toc: true
  license:
    enabled: true
    default: >-
      Licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0 "Learn more
      about the CC BY-SA 4.0 Licence.").
  math: false

dateFormat:
  published: January 02, 2006
  lastUpdated: January 02, 2006

widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 10
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc

footer:
  since: 2023
  customText: >-
    [Home](/ "Visit the homepage.") &sdot; 
    [About](/about "Learn more about me.") &sdot; 
    [Source Code](https://github.com/anipalur/anipalur.com "Visit the homepage.") &sdot; 
    [Disclaimer](/disclaimer "Learn more about the limitations of content on my blog.") &sdot; 
    [Privacy Policy](/privacy "Learn more about how your information is used on my blog.")
    <br />
    [RSS Feed](/index.xml "View the RSS feed for this blog.") &sdot; 
    [Sitemap](/sitemap.xml "View the sitemap for this blog.")

# Blog configuration
favicon: /favicon.svg
imageProcessing:
  cover:
    enabled: false
rssFullContent: true

defaultImage:
  opengraph:
    enabled: true
    src: img/anipalur-og-image.png
    local: true
    alt: The logo of Anitej Palur's blog.
opengraph:
  twitter:
    card: summary
