---
threshold: 60
includeNewer: true
toLower: true

indices:
  - name: categories
    toLower: false
    type: basic
    weight: 100
  - name: tags
    toLower: false
    type: basic
    weight: 75
  - name: fragmentrefs
    type: fragments
    weight: 50
  - name: date
    pattern: ""
    toLower: false
    type: basic
    weight: 25
